name: Gutenprint Printer
version: 5.3.4-11-edge
slug: gutenprint-printer
description: Printers using Gutenprint printer driver
url: https://github.com/Eskander/haos-printer
arch:
  - amd64
  - aarch64
stage: experimental
init: false
environment:
  PORT: "631"
webui: http://[HOST]:[PORT:631]
host_network: true
usb: true
map:
  - type: data
    path: /etc/cups/
    read_only: false
  - type: addon_config
    path: /var/lib/gutenprint-printer-app
    read_only: false
image: ghcr.io/openprinting/gutenprint-printer-app
